### 查询服务
GET 192.168.137.1:9001/imooc/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEyLFwidXNlcm5hbWVcIjpcIjhJbW9vY1FpbnlpQGltb29jLmNvbVwifSIsImp0aSI6ImQ0ZjU0M2I5LTY1MmItNDc3OC1iZTkxLTNjNzBhZGM4Y2I4NyIsImV4cCI6MTY0NjQ5NjAwMH0.RKQKOHMrNBXNeX0JGZB6eFqr-ZWcqTD-QN59re410_UnRWvkJ2WiBESE8WNl5pr4SRfsgH8BBK9xPbicU7RZ7KEGAk6l7lwGrAPliejOi65XwEAilb_uzQsjEnzCqSEoga3Bk9ugYS_rHw3sFTsp344d3ibapSlnnfJBhzATHGqmeBJgzO51jz77n4yZBn7N9z0TOzOs4gCQmVaGPMMti-hQdgniBMlXo9-_7bw-k-wut9liYbBmNBhCAYcs1lyKpNt8uh7iKCnFnTQZT0R64IbNEwVCC0MOTxA4o7R26bksnRcdxZHLmQm4XzCFijycqWbwTvoCkxfhrCvtcNdoPw
token: imooc
