spring:
  application:
    name: log-stack-springboot
  redis:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0

server:
  servlet:
    context-path: /api
  port: 8888
  tomcat:
    min-spare-threads: 500
    max-threads: 2500
    accept-count: 1000
    max-connections: 5000
  connection-timeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: "*" # 打开所有的监控点
  endpoint:
    health:
      show-details: always
