### 导入商品
POST http://127.0.0.1:9001/imooc/ecommerce-goods-service/async-goods/import-goods
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIkltb29jUWlueWlAaW1vb2MuY29tXCJ9IiwianRpIjoiMjM4ZTcxNzctOGZmYi00NGRhLWJkNDItYWRhMzZjNDk0NGEyIiwiZXhwIjoxNjQ2NjY4ODAwfQ.ksbw081sdR_vFnE_dNTFWMKa5bQdob1GIIXm1Zk0mhWrhV-HrZjLLXKX-bWAi6ICfxX2bSFUsgXZYMYcMbY6Rsg9iY1kMBvA-WK-MooZzkxmsziTSaDddBhXBjF5x_6Ip__7ikgAGlPVA8lI4WNRL4QUxjiA098S1MbyCXXsah1g6Dupbzh-XngAXy3_8_i8CJDZzx7lLTx3zitWE_spfVzJ3y4qZOf4JGJeCBDbZibzbpYQD1DyNdToqGRdCGIS6P5cDRIF_NWV1lngDIdcgLXGKGjYWhaXIx5dSUXpqLv911E-CqeBRgOvJOkjRrLSB30fAX3k0S1QfkWxhXZkpQ

[
  {
    "goodsCategory": "10001",
    "brandCategory": "20001",
    "goodsName": "iphone 11",
    "goodsPic": "",
    "goodsDescription": "苹果手机",
    "price": 100000,
    "supply": 2000000,
    "goodsProperty": {
      "size": "12cm * 6.5cm",
      "color": "绿色",
      "material": "金属机身",
      "pattern": "纯色"
    }
  },
  {
    "goodsCategory": "10001",
    "brandCategory": "20001",
    "goodsName": "iphone 12",
    "goodsPic": "",
    "goodsDescription": "苹果手机",
    "price": 150000,
    "supply": 2000000,
    "goodsProperty": {
      "size": "12cm * 6.5cm",
      "color": "绿色",
      "material": "金属机身",
      "pattern": "纯色"
    }
  },
  {
    "goodsCategory": "10001",
    "brandCategory": "20001",
    "goodsName": "iphone 13",
    "goodsPic": "",
    "goodsDescription": "苹果手机",
    "price": 160000,
    "supply": 2000000,
    "goodsProperty": {
      "size": "12cm * 6.5cm",
      "color": "绿色",
      "material": "金属机身",
      "pattern": "纯色"
    }
  }
]


### 查询导入商品状态
GET http://127.0.0.1:9001/imooc/ecommerce-goods-service/async-goods/task-info?taskId=06c40a3-eb35-44d6-8d87-934ba7f13cf0
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIkltb29jUWlueWlAaW1vb2MuY29tXCJ9IiwianRpIjoiMjM4ZTcxNzctOGZmYi00NGRhLWJkNDItYWRhMzZjNDk0NGEyIiwiZXhwIjoxNjQ2NjY4ODAwfQ.ksbw081sdR_vFnE_dNTFWMKa5bQdob1GIIXm1Zk0mhWrhV-HrZjLLXKX-bWAi6ICfxX2bSFUsgXZYMYcMbY6Rsg9iY1kMBvA-WK-MooZzkxmsziTSaDddBhXBjF5x_6Ip__7ikgAGlPVA8lI4WNRL4QUxjiA098S1MbyCXXsah1g6Dupbzh-XngAXy3_8_i8CJDZzx7lLTx3zitWE_spfVzJ3y4qZOf4JGJeCBDbZibzbpYQD1DyNdToqGRdCGIS6P5cDRIF_NWV1lngDIdcgLXGKGjYWhaXIx5dSUXpqLv911E-CqeBRgOvJOkjRrLSB30fAX3k0S1QfkWxhXZkpQ



###
GET http://localhost:8001/ecommerce-goods-service/220307/test1