spring:
  redis:
    host: @redis.host@
    port: @redis.port@
    jedis:
      pool:
        max-active: 8
        max-wait: 1000
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  data:
    mongodb:
      host: @mongo.host@
      port: @mongo.port@
      database: notice
#logging:
#  level:
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG