GET http://localhost:8083/220307/test1
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIkltb29jUWlueWlAaW1vb2MuY29tXCJ9IiwianRpIjoiMjM4ZTcxNzctOGZmYi00NGRhLWJkNDItYWRhMzZjNDk0NGEyIiwiZXhwIjoxNjQ2NjY4ODAwfQ.ksbw081sdR_vFnE_dNTFWMKa5bQdob1GIIXm1Zk0mhWrhV-HrZjLLXKX-bWAi6ICfxX2bSFUsgXZYMYcMbY6Rsg9iY1kMBvA-WK-MooZzkxmsziTSaDddBhXBjF5x_6Ip__7ikgAGlPVA8lI4WNRL4QUxjiA098S1MbyCXXsah1g6Dupbzh-XngAXy3_8_i8CJDZzx7lLTx3zitWE_spfVzJ3y4qZOf4JGJeCBDbZibzbpYQD1DyNdToqGRdCGIS6P5cDRIF_NWV1lngDIdcgLXGKGjYWhaXIx5dSUXpqLv911E-CqeBRgOvJOkjRrLSB30fAX3k0S1QfkWxhXZkpQ
