apiVersion: v1
kind: Service
metadata:
  name: service-session
  namespace: default
spec:
  selector:
     app: canary-nginx
  type: NodePort
  sessionAffinity: "ClientIP"
  sessionAffinityConfig:
    clientIP: 
      timeoutSeconds: 30
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
