version: '2'
services:
  tracker:
    image: season/fastdfs:1.2
    container_name: tracker
    restart: always
    volumes:
      - "./tracker_data:/fastdfs/tracker/data"
    ports: 
      - "22122:22122"
    command: "tracker" 
 
  storage:
    image: season/fastdfs:1.2
    container_name: storage
    links: 
      - tracker
    restart: always
    volumes:
      - "./storage.conf:/fdfs_conf/storage.conf"
      - "./storage_base_path:/fastdfs/storage/data"
      - "./store_path0:/fastdfs/store_path"  
    ports: 
      - "23000:23000"
    environment:
      TRACKER_SERVER: "tracker:22122"
    command: "storage"
 
  nginx:
    image: season/fastdfs:1.2
    container_name: fdfs-nginx
    restart: always
    volumes:
      - "./nginx.conf:/etc/nginx/conf/nginx.conf"
      - "./store_path0:/fastdfs/store_path"
    links: 
      - tracker
    ports: 
      - "8088:8088"
    environment:
      TRACKER_SERVER: "tracker:22122"
    command: "nginx"
