spring:
  application:
    name: delayed_exchange
  rabbitmq:
    host: handsomejay.work
    virtual-host: /
    username: admin
    password: admin
    port: 5672
#    listener:
#      simple:
#        acknowledge-mode: manual
