server:
  port: 9002

spring:
  application:
    name: pay-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/paydb
    username: root
    password: 1234


